# Copy this file as "config.yaml", and fill in the values as appropriate.
# ------------------------------------------------------------------------------

replacementDomains:
  - vxtwitter.com
  - fxtwitter.com
